routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();
Route::get('auth/{provider}', 'Auth\AuthController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\AuthController@handleProviderCallback');
Route::get('/setusertype/{type}',function($type){
    \Session::put('type',$type);
});
Route::get('setlanguage/{locale}', function ($locale) {
    App::setLocale($locale);
    LaravelLocalization::setLocale($locale);
    return LaravelLocalization::getCurrentLocale(); //App::getLocale();
});

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/privacy',function (){
    return response()->download('privacy.pdf');
});
Route::group([
    'prefix' => LaravelLocalization::setLocale()
],
    function() {
        Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );
        Auth::routes();
        Route::get('/','HomeController@index');
        Route::get("search","HomeController@Search");
        Route::get('users/{id}','UserController@show');
        Route::resource('category','CatgroyController');
        Route::get('exams/conditions/{id}','ExamController@conditions');
        Route::get('/terms',function(){
            return view('site.terms');
        });
    });
// Route::get('category/{slug}','CatgroyController@showact');
Route::group([
    'prefix' => LaravelLocalization::setLocale(),'middleware' => ['web','auth'],
],
    function() {
        Route::get('profile','UserController@profile');
        Route::get('profile/edit','UserController@editprofile');
        Route::resource('students','StudentController');
        Route::resource('exampublisher','ExamPublisherController');
        Route::get('exams/codepage','ExamController@codepage');
        Route::post('/exams/correct','ExamController@correct')->name('exams.correct');
        Route::resource('exams','ExamController');
        Route::get('exams/code/{id}','ExamController@code');
        Route::get('exam/pre','ExamController@exampre')->name('exams.precode');
        Route::get('exam/examprepage','ExamController@examprepage')->name('exams.examprepage');
        Route::get('exam/result','ExamController@examresult');
        Route::resource('questions','QuestionController');
        Route::post('/rate','RatingController@rate')->name('rate');
        Route::get('rateForm/','RatingController@rateForm');
        Route::get('follow/{following}/{follower}','UserController@follow');
        Route::resource('codes','CodesController');
        Route::get('publishexam/{code}','ExamController@publishexam');
        Route::get('getexamcodes/{code}','ExamController@getexamcodes');
        Route::post('/sharecode','ExamController@sharecode')->name('sharecode');
        Route::get('/examsolve/{code}','ExamController@examsolve');


});
Route::group(['as' => 'admin.',
    'prefix' => LaravelLocalization::setLocale().'/admin','middleware' => ['web','auth','admin'],
],
    function() {
        Route::get('/','Admin\HomeController@index');
        Route::resource('students','Admin\StudentController');
        Route::resource('exampublisher','Admin\ExamPublisherController');
        Route::resource('exams','Admin\ExamController');
        Route::resource('questions','Admin\QuestionController');
        Route::resource('users','Admin\UserController');
        Route::resource('category','Admin\CatgroyController');
        Route::resource('codes','Admin\CodesController');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Nicolaslopezj\Searchable\SearchableTrait;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable;
    use SearchableTrait;
    use HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $searchable = [
        'columns' => [
            'users.name' => 10,
            'users.email' => 10
        ]
    ];
    protected $fillable = [
        'name', 'email', 'password','provider','provider_id','profile','cover','type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function student(){
        return $this->hasOne('App\Models\Student');
    }
    public function exampublisher(){
        return $this->hasOne('App\Models\ExamPublisher');
    }
    public function examposted(){
        return $this->hasMany('App\Models\Exam');
    }
    public function exampassed(){
        return $this->belongsToMany('App\Models\Exam','user_exams')->withPivot('updated_at','points');
    }
    public function followers(){
        return $this->belongsToMany('App\User','follows','following_id','follower_id');
    }
    public function followings(){
        return $this->belongsToMany('App\User','follows','follower_id','following_id');
    }
    public function followcheck($id){
        $check=$this->followings->where('id',$id)->first();
        if($check){
            return true;
        }
        else{
            return false;
        }
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Flash;
use App\User;
use App\Models\Follow;
use App\Http\Controllers\Controller;
use App\DataTables\UsersDatatable;

class UserController extends Controller
{
    
    public function index(UsersDatatable $admin)
    {
        //
        if(isset($_GET['type']))
            $users=User::where('type',$_GET['type'])->get();
        else
            $users= User::all();
        return view('admin.users.index',compact('users'));
         

    }

    public function show($id)
    {
        //
        $user=User::find($id);
        if($user){
            if($user->type=='student'){
                return view('student.show',compact('user'));
            }
            else{
                return view('exampublisher.show',compact('user'));
            }

        }
        else{
            Flash::error('User not found');

            return back();
        }
    }
    public function profile(){
        $user=\Auth::user();
        if(\Auth::user()->type=='student'){
            return view('student.profile',compact('user'));
        }
        else{
            return view('exampublisher.profile',compact('user'));
        }
    }
    public function editprofile(){
        $user=\Auth::user();
        if(\Auth::user()->type=='student'){
            return view('student.edit',compact('user'));
        }
        else{
            return view('exampublisher.edit',compact('user'));
        }
    }

    public function follow($following,$follower){
        $follow=Follow::where([
            'follower_id'=>$follower,
            'following_id'=>$following
        ])->first();
        if($follow){
            $follow->forceDelete();
            return "Follow";
        }
        else{
            Follow::create([
                'follower_id'=>$follower,
                'following_id'=>$following
            ]);
            return "Following";
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Flash;
use App\User;
use App\Models\Follow;

class UserController extends Controller
{

    public function show($id)
    {
        $user = User::query()->find($id);
        if ($user) {
            if ($user->type == 'student') {
                return view('student.show', compact('user'));
            } else {
                return view('exampublisher.show', compact('user'));
            }
        } else {
            Flash::error('User not found');
            return back();
        }
    }

    public function profile()
    {
        $user = \Auth::user();
        if (\Auth::user()->type == 'student') {
            return view('student.profile', compact('user'));
        } elseif (\Auth::user()->type == 'exampublisher') {
            return view('exampublisher.profile', compact('user'));
        } else {
            return back();
        }
    }
    public function editprofile()
    {
        $user = \Auth::user();
        if (\Auth::user()->type == 'student') {
            return view('student.edit', compact('user'));
        } 
        elseif (\Auth::user()->type == 'exampublisher') {
            return view('exampublisher.edit', compact('user'));
        } else {
            return back();
        }
    }

    public function follow($following, $follower)
    {
        $follow = Follow::where([
            'follower_id' => $follower,
            'following_id' => $following
        ])->first();
        if ($follow) {
            $follow->forceDelete();
            return "Follow";
        } else {
            Follow::create([
                'follower_id' => $follower,
                'following_id' => $following
            ]);
            return "Following";
        }
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.index')
@section('content')


<div class="box">
  <div class="box-header">
    <h3 class="box-title">{{ $title }}</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    {!! Form::open(['url'=>aurl('users')]) !!}
     <div class="form-group">
        {!! Form::label('name',trans('admin.name')) !!}
        {!! Form::text('name',old('name'),['class'=>'form-control']) !!}
     </div>
     <div class="form-group">
        {!! Form::label('email',trans('admin.email')) !!}
        {!! Form::email('email',old('email'),['class'=>'form-control']) !!}
     </div>
     <div class="form-group">
        {!! Form::label('password',trans('admin.password')) !!}
        {!! Form::password('password',['class'=>'form-control']) !!}
     </div>

     <div class="form-group">
        {!! Form::label('level',trans('admin.level')) !!}
        {!! Form::select('level',['user'=>trans('admin.user'),'business'=>trans('admin.business')],old('level'),['class'=>'form-control','placeholder'=>'.............']) !!}
     </div>
     {!! Form::submit(trans('admin.add'),['class'=>'btn btn-primary']) !!}
    {!! Form::close() !!}
  </div>
  <!-- /.box-body -->
</div>
<!-- /.box -->



@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.index')
@section('content')


<div class="box">
  <div class="box-header">
    <h3 class="box-title">{{ $title }}</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    {!! Form::open(['url'=>aurl('users/'.$user->id),'method'=>'put' ]) !!}
     <div class="form-group">
        {!! Form::label('name',trans('admin.name')) !!}
        {!! Form::text('name',$user->name,['class'=>'form-control']) !!}
     </div>
     <div class="form-group">
        {!! Form::label('email',trans('admin.email')) !!}
        {!! Form::email('email',$user->email,['class'=>'form-control']) !!}
     </div>
     <div class="form-group">
        {!! Form::label('password',trans('admin.password')) !!}
        {!! Form::password('password',['class'=>'form-control']) !!}
     </div>

       <div class="form-group">
        {!! Form::label('level',trans('admin.level')) !!}
        {!! Form::select('level',['user'=>trans('admin.user'),'business'=>trans('admin.business')],$user->level,['class'=>'form-control','placeholder'=>'.............']) !!}
     </div>


     {!! Form::submit(trans('admin.save'),['class'=>'btn btn-primary']) !!}
    {!! Form::close() !!}
  </div>
  <!-- /.box-body -->
</div>
<!-- /.box -->



@endsection

resources/views/admin/users/index.blade.php
@extends('admin.index')
@section('content')
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Data Table With Full Features</h3>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <table id="example1" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Type</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($users as $user)
        <tr>
            <td>{{$user->name}}</td>
            <td>{{$user->email}}</td>
            <td>{{ $user->type}}</td>
            <td>
                {!! Form::open(['route' => ['admin.users.destroy', $user->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    {{-- <a href="{!! route('admin.users.show', [$user->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a> --}}
                    <a href="{!! route('admin.users.edit', [$user->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
          </tr>
        @endforeach
       
      </tbody>
      <tfoot>
      
      </tfoot>
    </table>
  </div>
  <!-- /.card-body -->
</div>

@endsection
@push('js')
  <script>
    $(function () {
      $('#example1').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false
      });
    });
  </script>
@endpush