routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();
Route::get('auth/{provider}', 'Auth\AuthController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\AuthController@handleProviderCallback');
Route::get('/setusertype/{type}',function($type){
    \Session::put('type',$type);
});
Route::get('setlanguage/{locale}', function ($locale) {
    App::setLocale($locale);
    LaravelLocalization::setLocale($locale);
    return LaravelLocalization::getCurrentLocale(); //App::getLocale();
});

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/privacy',function (){
    return response()->download('privacy.pdf');
});
Route::group([
    'prefix' => LaravelLocalization::setLocale()
],
    function() {
        Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );
        Auth::routes();
        Route::get('/','HomeController@index');
        Route::get("search","HomeController@Search");
        Route::get('users/{id}','UserController@show');
        Route::resource('category','CatgroyController');
        Route::get('exams/conditions/{id}','ExamController@conditions');
        Route::get('/terms',function(){
            return view('site.terms');
        });
    });
// Route::get('category/{slug}','CatgroyController@showact');
Route::group([
    'prefix' => LaravelLocalization::setLocale(),'middleware' => ['web','auth'],
],
    function() {
        Route::get('profile','UserController@profile');
        Route::get('profile/edit','UserController@editprofile');
        Route::resource('students','StudentController');
        Route::resource('exampublisher','ExamPublisherController');
        Route::get('exams/codepage','ExamController@codepage');
        Route::post('/exams/correct','ExamController@correct')->name('exams.correct');
        Route::resource('exams','ExamController');
        Route::get('exams/code/{id}','ExamController@code');
        Route::get('exam/pre','ExamController@exampre')->name('exams.precode');
        Route::get('exam/examprepage','ExamController@examprepage')->name('exams.examprepage');
        Route::get('exam/result','ExamController@examresult');
        Route::resource('questions','QuestionController');
        Route::post('/rate','RatingController@rate')->name('rate');
        Route::get('rateForm/','RatingController@rateForm');
        Route::get('follow/{following}/{follower}','UserController@follow');
        Route::resource('codes','CodesController');
        Route::get('publishexam/{code}','ExamController@publishexam');
        Route::get('getexamcodes/{code}','ExamController@getexamcodes');
        Route::post('/sharecode','ExamController@sharecode')->name('sharecode');
        Route::get('/examsolve/{code}','ExamController@examsolve');


});
Route::group(['as' => 'admin.',
    'prefix' => LaravelLocalization::setLocale().'/admin','middleware' => ['web','auth','admin'],
],
    function() {
        Route::get('/','Admin\HomeController@index');
        Route::resource('students','Admin\StudentController');
        Route::resource('exampublisher','Admin\ExamPublisherController');
        Route::resource('exams','Admin\ExamController');
        Route::resource('questions','Admin\QuestionController');
        Route::resource('users','Admin\UserController');
        Route::resource('category','Admin\CatgroyController');
        Route::resource('codes','Admin\CodesController');

});

app/Models/Category.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Nicolaslopezj\Searchable\SearchableTrait;
/**
 * Class Category
 * @package App\Models
 * @version October 18, 2016, 1:20 pm UTC
 */
class Category extends Model
{
    use SearchableTrait;
    public $table = 'categories';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];

    protected $searchable = [
        'columns' => [
            'categories.name_en' => 10,
            'categories.name_ar' => 10
        ]
    ];
    public $fillable = [
        'name_en',
        'name_ar',
        'slug',
        'descrpition',
        'image'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'slug' => 'string',
        'descrpition' => 'text'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name_en'=>'required|min:2|unique:categories,name_en',
        'name_ar'=>'required|min:2,'
    ];

    protected $appends = array('topcategory','name');
    public function exams()
    {
        return $this->hasMany(\App\Models\Exam::class);
    }
    public function getTopcategoryAttribute(){
        return count($this->exams);
    }
    public function getNameAttribute(){
        $name = 'name_'.\App::getLocale();
        return $this->$name;
    }



}

resources/views/admin/categories/create.blade.php
@extends('admin.index')
@section('content')


<div class="box">
  <div class="box-header">
    <h3 class="box-title">Add New Category </h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    {!! Form::open(['url'=>'admin/category']) !!}
      <div class="form-group">
        {!! Form::label('name_en','Name In English') !!}
        {!! Form::text('name_en',old('name_en'),['class'=>'form-control','id'=>'catname']) !!}
      </div>
      <div class="form-group">
        {!! Form::label('name_ar','الاسم بالعربى') !!}
        {!! Form::text('name_ar',old('name_ar'),['class'=>'form-control']) !!}
      </div>
      <div class="form-group">
        {!! Form::label('slug','Slug:') !!}
        {!! Form::text('slug',null,['class'=>'form-control','id'=>'slug','readonly']) !!}
      </div>
     <div class="form-group">
        {!! Form::label('descrpition','Descrpition:') !!}
        {!! Form::textarea('descrpition',null,['class'=>'form-control']) !!}
      </div>
     {!! Form::submit(trans('website.save'),['class'=>'btn btn-primary']) !!}
    {!! Form::close() !!}
  </div>
  <!-- /.box-body -->
</div>
<!-- /.box -->



@endsection
@push('js')
<script>
  $(document).on('keypress change','#catname',function(){
        var slug=string_to_slug($('#catname').val());
        $('#slug').val(slug);
    });
    function string_to_slug (str) {
        str = str.replace(/^\s+|\s+$/g, ''); // trim
        str = str.toLowerCase();
    
        // remove accents, swap ñ for n, etc
        var from = "àáäâèéëêìíïîòóöôùúüûñç·/_,:;";
        var to   = "aaaaeeeeiiiioooouuuunc";
        for (var i=0, l=from.length ; i<l ; i++) {
            str = str.replace(new RegExp(from.charAt(i), 'g'), to.charAt(i));
        }

        str = str.replace(/[^a-z0-9 -]/g, '') // remove invalid chars
            .replace(/\s+/g, '') // collapse whitespace and replace by -
            .replace(/-+/g, ''); // collapse dashes

        return str;
    }
</script>
@endpush

resources/views/admin/categories/edit.blade.php
@extends('admin.index')
@section('content')


<div class="box">
  <div class="box-header">
    <h3 class="box-title">Edit Category</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    {!! Form::model($category,['url'=>'admin/category/'.$category->id,'method'=>'put' ]) !!}
    <div class="form-group">
      {!! Form::label('name_en','Name In English') !!}
      {!! Form::text('name_en',old('name_en'),['class'=>'form-control','id'=>'catname']) !!}
    </div>
    <div class="form-group">
      {!! Form::label('name_ar','الاسم بالعربى') !!}
      {!! Form::text('name_ar',old('name_ar'),['class'=>'form-control']) !!}
    </div>
   <div class="form-group">
      {!! Form::label('descrpition','Descrpition:') !!}
      {!! Form::textarea('descrpition',null,['class'=>'form-control']) !!}
   </div>
   {!! Form::submit(trans('website.save'),['class'=>'btn btn-primary']) !!}
    {!! Form::close() !!}
  </div>
  <!-- /.box-body -->
</div>
<!-- /.box -->



@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.index')
@section('content')
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Categories</h3>
    <a href="/admin/category/create"> Add New</a>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <table id="example1" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Slug</th>
          <th>Descrpition</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($categories as $category)
        <tr>
            <td>{{$category->name}}</td>
            <td>{{$category->slug}}</td>
            <td>{{ $category->descrpition}}</td>
            <td>
                {!! Form::open(['route' => ['admin.category.destroy', $category->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('admin.category.show', [$category->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('admin.category.edit', [$category->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
          </tr>
        @endforeach
       
      </tbody>
      <tfoot>
      
      </tfoot>
    </table>
  </div>
  <!-- /.card-body -->
</div>

@endsection
@push('js')
  <script>
    $(function () {
      $('#example1').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false
      });
    });
  </script>
@endpush